#!/bin/bash
#requires plymouth-x11 installed
#sudo apt-get install plymouth-x11
TIME=8
echo
echo "Running $TIME-second test..."
sudo plymouthd ; sudo plymouth --show-splash ; for ((I=0; I<$TIME; I++)); do sleep 1 ; sudo plymouth --update=test$I ; done ; sudo plymouth --quit
exit
